application: helloworld
version: 1
runtime: php
api_version: 1

handlers:
# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /commingsoon1
  static_files: commingsoon1.html
  upload: commingsoon1.html

- url: /commingsoon2
  static_files: commingsoon2.html
  upload: commingsoon2.html

- url: /plexx
  static_files: plexx.html
  upload: plexx.html

- url: /(.*)
  static_files: \1
  upload: (.*)
