application: annular-aria-650
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /(.*)
  static_files: \1
  upload: (.*)
